-- Tabla de Trabajadores
CREATE TABLE IF NOT EXISTS trabajadores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dni VARCHAR(20) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100),
    nombre_completo VARCHAR(250),
    fecha_nacimiento DATE,
    lugar_nacimiento VARCHAR(200),
    nacionalidad VARCHAR(100) DEFAULT 'Peruana',
    sexo ENUM('M', 'F', 'Otro') DEFAULT 'M',
    estado_civil ENUM('Soltero', 'Casado', 'Divorciado', 'Viudo', 'Otro') DEFAULT 'Soltero',
    telefono VARCHAR(20),
    celular VARCHAR(20),
    email VARCHAR(200),
    direccion TEXT,
    distrito VARCHAR(100),
    provincia VARCHAR(100),
    departamento VARCHAR(100),
    area_id INT,
    puesto VARCHAR(150),
    fecha_ingreso DATE NOT NULL,
    fecha_cese DATE,
    tipo_contrato ENUM('Indefinido', 'Temporal', 'Prácticas', 'Por Proyecto', 'Otro') DEFAULT 'Indefinido',
    estado ENUM('Activo', 'Inactivo', 'Vacaciones', 'Licencia', 'Cesado') DEFAULT 'Activo',
    observaciones TEXT,
    emergencia_nombre VARCHAR(200),
    emergencia_telefono VARCHAR(20),
    emergencia_parentesco VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by INT,
    INDEX idx_dni (dni),
    INDEX idx_estado (estado),
    INDEX idx_area (area_id),
    INDEX idx_fecha_ingreso (fecha_ingreso),
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
